; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
tick_counter:
	DW	0
	ALIGN	2
reset:
	; >>>>> Line:	5
	; >>>>> void reset() { 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	6
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
L_myinth_4:
	DB	"TICK ",0
	ALIGN	2
tick:
	; >>>>> Line:	9
	; >>>>> void tick() { 
	jmp	L_myinth_5
L_myinth_6:
	; >>>>> Line:	10
	; >>>>> tick_counter++; 
	inc	word [tick_counter]
	; >>>>> Line:	11
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	12
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	13
	; >>>>> printUInt(tick_counter); 
	push	word [tick_counter]
	call	printUInt
	add	sp, 2
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_myinth_5:
	push	bp
	mov	bp, sp
	jmp	L_myinth_6
L_myinth_11:
	DB	"DELAY COMPLETE",0
L_myinth_10:
	DB	"DELAY KEY PRESSED",0
L_myinth_9:
	DB	") IGNORED",0
L_myinth_8:
	DB	"KEPYRESS (",0
	ALIGN	2
keyboard:
	; >>>>> Line:	17
	; >>>>> void keyboard() { 
	jmp	L_myinth_12
L_myinth_13:
	; >>>>> Line:	19
	; >>>>> if (KeyBuffer != 'd') { 
	mov	word [bp-2], 0
	; >>>>> Line:	19
	; >>>>> if (KeyBuffer != 'd') { 
	cmp	word [KeyBuffer], 100
	je	L_myinth_14
	; >>>>> Line:	20
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	21
	; >>>>> printString("KEPYRESS ("); 
	mov	ax, L_myinth_8
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	22
	; >>>>> printChar(KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	23
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_myinth_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	24
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_myinth_15
L_myinth_14:
	; >>>>> Line:	26
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	27
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_myinth_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	28
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	29
	; >>>>> while (delayCounter <= 5000) { 
	jmp	L_myinth_17
L_myinth_16:
	; >>>>> Line:	30
	; >>>>> delayCounter++; 
	inc	word [bp-2]
L_myinth_17:
	cmp	word [bp-2], 5000
	jle	L_myinth_16
L_myinth_18:
	; >>>>> Line:	32
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_myinth_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> p 
	call	printNewLine
L_myinth_15:
	mov	sp, bp
	pop	bp
	ret
L_myinth_12:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_13
