; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
tmp:
prev:
	DW	0
state:
	DW	3
pend:
next:
	DW	0
prev:
	DW	0
tmp2:
tmp3:
next:
prev:
next:
	DW	0
next:
prev:
prev:
pend:
next:
tmp:
pend:
prev:
	DW	0
state:
	DW	1
tmp2:
tmp2:
YKRdyList:
next:
prev:
next:
prev:
msgtmp:
next_out:
	DW	0